version: "3"

services:
  cyphernode_welcome:
    environment:
      - "TRACING=1"
      - "CYPHERNODE_URL=https://gatekeeper:${GATEKEEPER_PORT}"
    image: cyphernode/app_welcome:v0.2.4
    volumes:
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/data/cert.pem"
      - "$GATEKEEPER_DATAPATH/keys.properties:/data/keys.properties"
      - "$APP_SCRIPT_PATH/config.toml:/data/config.toml"
      - "$GATEKEEPER_DATAPATH/htpasswd:/htpasswd/htpasswd"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=cyphernodeappsnet
      - traefik.http.routers.cyphernode_welcome.rule=PathPrefix(`/welcome`)
      - traefik.http.routers.cyphernode_welcome.entrypoints=websecure
      - traefik.http.routers.cyphernode_welcome.tls=true
      - traefik.http.routers.cyphernode_welcome.service=cyphernode_welcome
      - traefik.http.routers.cyphernode_welcome.middlewares=cyphernode_welcome-stripprefix@docker,cyphernode_welcome-auth@docker
      - traefik.http.routers.cyphernode_welcome-onion.rule=PathPrefix(`/welcome`)
      - traefik.http.routers.cyphernode_welcome-onion.entrypoints=onion
      - traefik.http.routers.cyphernode_welcome-onion.service=cyphernode_welcome
      - traefik.http.routers.cyphernode_welcome-onion.middlewares=cyphernode_welcome-stripprefix@docker,cyphernode_welcome-auth@docker
      - traefik.http.services.cyphernode_welcome.loadbalancer.server.port=8080
      - traefik.http.middlewares.cyphernode_welcome-stripprefix.stripprefix.prefixes=/welcome,/welcome/
      - traefik.http.middlewares.cyphernode_welcome-stripprefix.stripprefix.forceSlash=true
      - traefik.http.middlewares.cyphernode_welcome-auth.basicauth.usersfile=/htpasswd/htpasswd
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=cyphernodeappsnet
        - traefik.http.routers.cyphernode_welcome.rule=PathPrefix(`/welcome`)
        - traefik.http.routers.cyphernode_welcome.entrypoints=websecure
        - traefik.http.routers.cyphernode_welcome.tls=true
        - traefik.http.routers.cyphernode_welcome.service=cyphernode_welcome
        - traefik.http.routers.cyphernode_welcome.middlewares=cyphernode_welcome-stripprefix@docker,cyphernode_welcome-auth@docker
        - traefik.http.routers.cyphernode_welcome-onion.rule=PathPrefix(`/welcome`)
        - traefik.http.routers.cyphernode_welcome-onion.entrypoints=onion
        - traefik.http.routers.cyphernode_welcome-onion.service=cyphernode_welcome
        - traefik.http.routers.cyphernode_welcome-onion.middlewares=cyphernode_welcome-stripprefix@docker,cyphernode_welcome-auth@docker
        - traefik.http.services.cyphernode_welcome.loadbalancer.server.port=8080
        - traefik.http.middlewares.cyphernode_welcome-stripprefix.stripprefix.prefixes=/welcome,/welcome/
        - traefik.http.middlewares.cyphernode_welcome-stripprefix.stripprefix.forceSlash=true
        - traefik.http.middlewares.cyphernode_welcome-auth.basicauth.usersfile=/htpasswd/htpasswd
      replicas: 1
      placement:
        constraints:
          - node.labels.io.cyphernode == true
      restart_policy:
        condition: "any"
        delay: 1s
      update_config:
        parallelism: 1
networks:
  cyphernodeappsnet:
    external: true
