version: "3"

services:
  batcher:
    environment:
      - "TRACING=1"
      - "CYPHERNODE_URL=https://gatekeeper:${GATEKEEPER_PORT}"
    image: cyphernode/batcher:v0.2.1
    entrypoint: ["npm", "run", "start:dev"]
    volumes:
      - "$APP_SCRIPT_PATH/data:/batcher/data"
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/batcher/cert.pem:ro"
      - "$LOGS_DATAPATH:/batcher/logs"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=cyphernodeappsnet

      - traefik.http.routers.batcher.rule=PathPrefix(`/batcher`)
      - traefik.http.routers.batcher.entrypoints=websecure
      - traefik.http.routers.batcher.tls=true
      - traefik.http.routers.batcher.service=batcher
      - traefik.http.routers.batcher.middlewares=batcher-redirectregex@docker,batcher-stripprefix@docker,batcher-auth@docker

      - traefik.http.routers.batcher-onion.rule=PathPrefix(`/batcher`)
      - traefik.http.routers.batcher-onion.entrypoints=onion
      - traefik.http.routers.batcher-onion.service=batcher
      - traefik.http.routers.batcher-onion.middlewares=batcher-redirectregex@docker,batcher-stripprefix@docker,batcher-auth@docker

      - traefik.http.services.batcher.loadbalancer.server.port=8000
      - traefik.http.services.batcher.loadbalancer.passHostHeader=true

      - traefik.http.middlewares.batcher-redirectregex.redirectregex.regex=^(.*)/batcher$$
      - traefik.http.middlewares.batcher-redirectregex.redirectregex.replacement=$$1/batcher/
      - traefik.http.middlewares.batcher-redirectregex.redirectregex.permanent=true
      - traefik.http.middlewares.batcher-stripprefix.stripprefix.prefixes=/batcher,/batcher/
      # - traefik.http.middlewares.batcher-stripprefix.stripprefix.forceSlash=true
      - traefik.http.middlewares.batcher-auth.basicauth.users=<username:bcrypt>
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=cyphernodeappsnet

        - traefik.http.routers.batcher.rule=PathPrefix(`/batcher`)
        - traefik.http.routers.batcher.entrypoints=websecure
        - traefik.http.routers.batcher.tls=true
        - traefik.http.routers.batcher.service=batcher
        - traefik.http.routers.batcher.middlewares=batcher-redirectregex@docker,batcher-stripprefix@docker,batcher-auth@docker

        - traefik.http.routers.batcher-onion.rule=PathPrefix(`/batcher`)
        - traefik.http.routers.batcher-onion.entrypoints=onion
        - traefik.http.routers.batcher-onion.service=batcher
        - traefik.http.routers.batcher-onion.middlewares=batcher-redirectregex@docker,batcher-stripprefix@docker,batcher-auth@docker

        - traefik.http.services.batcher.loadbalancer.server.port=8000
        - traefik.http.services.batcher.loadbalancer.passHostHeader=true

        - traefik.http.middlewares.batcher-redirectregex.redirectregex.regex=^(.*)/batcher$$
        - traefik.http.middlewares.batcher-redirectregex.redirectregex.replacement=$$1/batcher/
        - traefik.http.middlewares.batcher-redirectregex.redirectregex.permanent=true
        - traefik.http.middlewares.batcher-stripprefix.stripprefix.prefixes=/batcher,/batcher/
        # - traefik.http.middlewares.batcher-stripprefix.stripprefix.forceSlash=true
        - traefik.http.middlewares.batcher-auth.basicauth.users=<username:bcrypt>
      replicas: 1
      placement:
        constraints:
          - node.labels.io.cyphernode == true
      restart_policy:
        delay: 1s
      update_config:
        parallelism: 1
networks:
  cyphernodeappsnet:
    external: true
